language: cpp

cache:
  directories:
    - travis-cache

os:
  - linux
  - osx

dist: xenial

compiler:
  - gcc
  - clang

env:
  - CONFIG=Debug
  - CONFIG=RelWithDebInfo

matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
      - pv
  homebrew:
    packages:
      - pv
    update: true

before_script:
  - scripts/configure_travis.sh .

script:
  - cmake --build .
  - ctest

after_success:
  - travis_after_success.sh .

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GHPAGES_DOCS_TOKEN
  keep_history: true
  local_dir: html
  repo: samwarring/hotplate-docs
  target_branch: master
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux && $CONFIG = RelWithDebInfo
