language: cpp

cache:
  directories:
    - travis-cache

os:
  - linux
  - osx

dist: xenial

compiler:
  - gcc
  - clang

env:
  - CONFIG=Debug
  - CONFIG=RelWithDebInfo

matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
      - pv

before_script:
  - scripts/configure_travis.sh .

script:
  - cmake --build .
  - ctest
