language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - CONFIG=Debug
  - CONFIG=RelWithDebInfo

matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
      - libboost-all-dev
	  
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$CONFIG

script:
  - cmake --build .
  - ctest
