version: '0.0.0.{build}'

image: Visual Studio 2015

platform:
  - x64
 
configuration:
  - RelWithDebInfo
  - Debug

before_build:
  - scripts\appveyor_before_build.bat

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - scripts\appveyor_test_script.bat
