version: '0.0.0.{build}'

image: Visual Studio 2015

platform:
  - x64
 
configuration:
  - RelWithDebInfo
  - Debug

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DBOOST_ROOT=C:\Libraries\boost_1_69_0 ..

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - dumpbin /imports %CONFIGURATION%\hotplate_boost_test.exe
  - ctest -C %CONFIGURATION% --verbose
